version: "3"

services:
    telegraf:
        build: ./telegraf
        container_name: ${CONTAINER_PREFIX}_telegraf
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: always
        env_file:
            - .env
        network_mode: "host"

networks:
    backend:
    frontend:
